apiVersion: v1
kind: Pod
metadata:
  name: jumpbox
spec:
  containers:
  - name: jumpbox
    image: ubuntu
    imagePullPolicy: Always
    command:
    - /bin/bash
    - -c
    args:
    - >
      apt-get update &&
      apt-get install -y mysql-client curl &&
      sleep 3600
